# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
yum install -y epel-release
yum update
yum install -y gcc python-devel openssl-devel python2-pip git
pip install --upgrade pip
pip install ansible
cd /root && git clone https://github.com/dmbrownlee/centiso.git
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  #config.vm.synced_folder ".", "/var/centiso"

  # VM to build the custom Centos ISO
  config.vm.define "buildbox" do |node|
    node.vm.box = "centos/7"
    node.vm.provider "virtualbox" do |vb|
      vb.name = "buildbox"
      vb.memory = 2048
      vb.cpus = 2
      vb.gui = true
    end
    node.vm.provision "shell", inline: $script
  end
end
