#!/bin/bash
BASEURL=rsync://centos.mirrors.tds.net/centos/7.3.1611
LOCALDIR=/var/www/html/repos/centos/7

for repo in os updates centosplus extras; do
  rsync -avz --exlcude-from=/etc/syncrepos/excludes/$repo.list \
    $BASEURL/$repo/x86_64/ $LOCALDIR/$repo/x86_64/
done

